[package]
name = "rocket-json-response"
version = "0.5.10"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/rocket-json-response"
homepage = "https://magiclen.org/rocket-json-response"
keywords = ["rocket", "server", "web", "json"]
categories = ["web-programming"]
description= "This is a crate which provides `JSONResponse` and `JSONResponseWithoutData` structs to response JSON format data with an additional **code** integer value."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/rocket-json-response"
branch = "master"

[dependencies]
rocket = "0.4.2"
debug-helper = "0.3"

[dev-dependencies]
serde = "1"
serde_derive = "1"
enum-ordinalize = "2"

[dependencies.json-gettext]
version = "3"
features = ["rocketly"]